LearnStack/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from apps.students.views import RoleBasedLoginView


urlpatterns = [
    path("accounts/login/", RoleBasedLoginView.as_view(), name="login"),
    path(
        "accounts/logout/",
        auth_views.LogoutView.as_view(next_page="courses:list"),
        name="logout",
    ),
    path("admin/", admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path(
        "courses/",
        include(("apps.courses.urls", "courses"), namespace="courses"),
    ),
    path(
        "students/",
        include(("apps.students.urls", "students"), namespace="students"),
    ),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

apps/students/urls.py
from django.urls import path

from . import views

app_name = "students"
urlpatterns = [
    path(
        "register/",
        views.StudentRegistrationView.as_view(),
        name="registration",
    ),
    path(
        "enroll-course/",
        views.StudentEnrollCourseView.as_view(),
        name="enroll_course",
    ),
    path(
        "courses/",
        views.StudentCourseListView.as_view(),
        name="course_list",
    ),
    path(
        "courses/<pk>/",
        views.StudentCourseDetailView.as_view(),
        name="course_detail",
    ),
    path(
        "courses/<pk>/<module_id>/",
        views.StudentCourseDetailView.as_view(),
        name="module_content",
    ),
]

apps/students/models.py
from django.db import models

# Create your models here.

apps/students/forms.py
from django import forms
from apps.courses.models import Course


class CourseEnrollForm(forms.Form):
    course = forms.ModelChoiceField(
        queryset=Course.objects.none(), widget=forms.HiddenInput
    )

    def __init__(self, *args, **kwargs):
        super(CourseEnrollForm, self).__init__(*args, **kwargs)
        self.fields["course"].queryset = Course.objects.all()

apps/students/views.py
from django.contrib.auth import login
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.views.generic.edit import CreateView, FormView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

from .forms import CourseEnrollForm
from apps.courses.models import Course


class RoleBasedLoginView(LoginView):
    def get_success_url(self):
        if self.request.user.is_staff:
            return reverse_lazy("courses:manage")
        return reverse_lazy("students:course_list")


class StudentRegistrationView(CreateView):
    form_class = UserCreationForm
    template_name = "students/student/registration_form.html"

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_staff = False
        user.is_superuser = False
        user.save()
        login(self.request, user)
        return redirect(self.get_success_url())

    def get_success_url(self):
        if self.request.user.is_staff:
            return reverse_lazy("courses:manage")
        return reverse_lazy("students:course_list")


class StudentEnrollCourseView(LoginRequiredMixin, FormView):
    course = None
    form_class = CourseEnrollForm

    def form_valid(self, form):
        self.course = form.cleaned_data["course"]
        self.course.students.add(self.request.user)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("students:course_detail", args=[self.course.id])


class StudentCourseListView(LoginRequiredMixin, ListView):
    model = Course
    template_name = "students/course/list.html"

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(students__in=[self.request.user])


class StudentCourseDetailView(LoginRequiredMixin, DetailView):
    model = Course
    template_name = "students/course/detail.html"

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(students__in=[self.request.user])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # получить текущий курс
        course = self.get_object()
        if "module_id" in self.kwargs:
            # загрузить конкретный модуль
            context["module"] = course.modules.get(id=self.kwargs["module_id"])
        else:
            # загрузить первый модуль
            context["module"] = course.modules.all()[0]
        return context

apps/students/templates/students/course/detail.html
{% extends "base.html" %}
{% load cache %}

{% block title %}
  {{ object.title }}
{% endblock %}

{% block content %}
  <h1>
    {{ module.title }}
  </h1>
  <div class="contents">
    <h3>Модули</h3>
    <ul id="modules">
      {% for m in object.modules.all %}
        <li data-id="{{ m.id }}" {% if m == module %}class="selected"{% endif %}>
          <a href="{% url "students:module_content" object.id m.id %}">
            <span>
              Модуль <span class="order">{{ m.order|add:1 }}</span>
            </span>
            <br>
            {{ m.title }}
          </a>
        </li>
      {% empty %}
        <li>Нет модулей.</li>
      {% endfor %}
    </ul>
  </div>
  <div class="module">
    {% cache 600 module_contents module %}
      {% for content in module.contents.all %}
        {% with item=content.item %}
          <h2>{{ item.title }}</h2>
          {{ item.render }}
        {% endwith %}
      {% endfor %}
    {% endcache %}
  </div>
{% endblock %}

apps/students/templates/students/course/list.html
{% extends "base.html" %}

{% block title %}Мои курсы{% endblock %}

{% block content %}
  <h1>Мои курсы</h1>
  <div class="module">
    {% for course in object_list %}
      <div class="course-info">
        <h3>{{ course.title }}</h3>
        <p><a href="{% url "students:course_detail" course.id %}">
        Доступ к содержимому</a></p>
      </div>
    {% empty %}
      <p>
        Вы не подписаны ни на один курс.
        <a href="{% url "courses:list" %}">Посмотреть курсы</a>
        чтобы подписаться на курс.
      </p>
    {% endfor %}
  </div>
{% endblock %}